USE [master]
GO
/****** Object:  Database [RecipeDataBase]    Script Date: 07.02.2025 13:32:37 ******/
CREATE DATABASE [RecipeDataBase]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'hellodb', FILENAME = N'G:\Programs\MSQLServerManagmentStudio\MSSQL16.MSSQLSERVER\MSSQL\DATA\hellodb.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'hellodb_log', FILENAME = N'G:\Programs\MSQLServerManagmentStudio\MSSQL16.MSSQLSERVER\MSSQL\DATA\hellodb_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [RecipeDataBase] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [RecipeDataBase].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [RecipeDataBase] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [RecipeDataBase] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [RecipeDataBase] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [RecipeDataBase] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [RecipeDataBase] SET ARITHABORT OFF 
GO
ALTER DATABASE [RecipeDataBase] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [RecipeDataBase] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [RecipeDataBase] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [RecipeDataBase] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [RecipeDataBase] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [RecipeDataBase] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [RecipeDataBase] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [RecipeDataBase] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [RecipeDataBase] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [RecipeDataBase] SET  ENABLE_BROKER 
GO
ALTER DATABASE [RecipeDataBase] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [RecipeDataBase] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [RecipeDataBase] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [RecipeDataBase] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [RecipeDataBase] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [RecipeDataBase] SET READ_COMMITTED_SNAPSHOT ON 
GO
ALTER DATABASE [RecipeDataBase] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [RecipeDataBase] SET RECOVERY FULL 
GO
ALTER DATABASE [RecipeDataBase] SET  MULTI_USER 
GO
ALTER DATABASE [RecipeDataBase] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [RecipeDataBase] SET DB_CHAINING OFF 
GO
ALTER DATABASE [RecipeDataBase] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [RecipeDataBase] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [RecipeDataBase] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [RecipeDataBase] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'RecipeDataBase', N'ON'
GO
ALTER DATABASE [RecipeDataBase] SET QUERY_STORE = ON
GO
ALTER DATABASE [RecipeDataBase] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [RecipeDataBase]
GO
/****** Object:  Table [dbo].[Ingredient]    Script Date: 07.02.2025 13:32:37 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Ingredient](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](max) NULL,
 CONSTRAINT [PK_Ingredient] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Recipe]    Script Date: 07.02.2025 13:32:37 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Recipe](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](max) NULL,
	[Actions] [nvarchar](max) NULL,
 CONSTRAINT [PK_Recipe] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[RecipeIngredient]    Script Date: 07.02.2025 13:32:37 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[RecipeIngredient](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[IdRecipe] [int] NOT NULL,
	[IdIngredient] [int] NOT NULL,
 CONSTRAINT [PK_RecipeIngredient] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET IDENTITY_INSERT [dbo].[Ingredient] ON 
GO
INSERT [dbo].[Ingredient] ([Id], [Name]) VALUES (1, N'nnnnnn')
GO
INSERT [dbo].[Ingredient] ([Id], [Name]) VALUES (2, N'dfgdfgdgdg')
GO
SET IDENTITY_INSERT [dbo].[Ingredient] OFF
GO
SET IDENTITY_INSERT [dbo].[Recipe] ON 
GO
INSERT [dbo].[Recipe] ([Id], [Name], [Actions]) VALUES (1, N'dsddddd', N'15434535')
GO
SET IDENTITY_INSERT [dbo].[Recipe] OFF
GO
SET IDENTITY_INSERT [dbo].[RecipeIngredient] ON 
GO
INSERT [dbo].[RecipeIngredient] ([Id], [IdRecipe], [IdIngredient]) VALUES (1, 1, 1)
GO
INSERT [dbo].[RecipeIngredient] ([Id], [IdRecipe], [IdIngredient]) VALUES (2, 1, 2)
GO
SET IDENTITY_INSERT [dbo].[RecipeIngredient] OFF
GO
ALTER TABLE [dbo].[RecipeIngredient]  WITH CHECK ADD  CONSTRAINT [FK_RecipeIngredient_Ingredient] FOREIGN KEY([IdIngredient])
REFERENCES [dbo].[Ingredient] ([Id])
GO
ALTER TABLE [dbo].[RecipeIngredient] CHECK CONSTRAINT [FK_RecipeIngredient_Ingredient]
GO
ALTER TABLE [dbo].[RecipeIngredient]  WITH CHECK ADD  CONSTRAINT [FK_RecipeIngredient_Recipe] FOREIGN KEY([IdRecipe])
REFERENCES [dbo].[Recipe] ([Id])
GO
ALTER TABLE [dbo].[RecipeIngredient] CHECK CONSTRAINT [FK_RecipeIngredient_Recipe]
GO
USE [master]
GO
ALTER DATABASE [RecipeDataBase] SET  READ_WRITE 
GO
