USE master
GO

CREATE DATABASE RecipeDataBase

USE RecipeDataBase

CREATE TABLE MeasureUnit(
	Id		INT PRIMARY KEY IDENTITY,
	[Name]	NVARCHAR(16) NOT NULL
)
CREATE TABLE Ingredient(
	Id				INT PRIMARY KEY IDENTITY,
	[Name]			NVARCHAR(200) NOT NULL,
	IdMeasureUnit	INT,
	FOREIGN KEY(IdMeasureUnit) REFERENCES MeasureUnit
)
CREATE TABLE Recipe(
	Id		INT PRIMARY KEY IDENTITY,
	[Name]	NVARCHAR(200) NOT NULL,
	Actions	NVARCHAR(200) NOT NULL
)

CREATE TABLE RecipeIngredient(
	Id				INT PRIMARY KEY IDENTITY,
	IdRecipe		INT NOT NULL,
	IdIngredient	INT NOT NULL,
	FOREIGN KEY (IdRecipe) 		REFERENCES Recipe,
	FOREIGN KEY (IdIngredient)	REFERENCES Ingredient
)

CREATE TABLE Recipe